"""主にuservitalcategoryを追加した

Revision ID: 85141f7a8f14
Revises: af2eabdddb1e
Create Date: 2025-07-08 13:50:50.165182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85141f7a8f14'
down_revision: Union[str, Sequence[str], None] = 'af2eabdddb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitaldata', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_vitaldata_user_id", 'users', ['user_id'], ['id'])
        batch_op.drop_column('is_accumulating')
        batch_op.drop_column('is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitaldata', sa.Column('is_public', sa.BOOLEAN(), nullable=False))
    op.add_column('vitaldata', sa.Column('is_accumulating', sa.BOOLEAN(), nullable=False))
    op.drop_constraint(None, 'vitaldata', type_='foreignkey')
    op.drop_column('vitaldata', 'user_id')
    # ### end Alembic commands ###