"""Userテーブルにiconとheightの追加

Revision ID: af2eabdddb1e
Revises: 0bda397b3345
Create Date: 2025-07-01 21:54:33.065378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2eabdddb1e'
down_revision: Union[str, Sequence[str], None] = '0bda397b3345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_column('users', 'icon')
    # ### end Alembic commands ###
