"""Add chat conversation and message tables

Revision ID: b277e46d1a8f
Revises: cb9c7f21025e
Create Date: 2025-07-15 17:07:36.966515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b277e46d1a8f'
down_revision: Union[str, Sequence[str], None] = 'cb9c7f21025e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
