"""vitaldata にuser_id カラムを追加

Revision ID: cb9c7f21025e
Revises: 335ee904e83c
Create Date: 2025-07-08 17:51:04.914129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9c7f21025e'
down_revision: Union[str, Sequence[str], None] = '335ee904e83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing rows
    op.add_column('vitaldata', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('vitaldata', sa.Column('is_accumulating', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('vitaldata', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='1'))
    
    # Remove server defaults after adding columns
    op.alter_column('vitaldata', 'user_id', server_default=None)
    op.alter_column('vitaldata', 'is_accumulating', server_default=None)
    op.alter_column('vitaldata', 'is_public', server_default=None)
    
    op.create_foreign_key(None, 'vitaldata', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitaldata', type_='foreignkey')
    op.drop_column('vitaldata', 'is_public')
    op.drop_column('vitaldata', 'is_accumulating')
    op.drop_column('vitaldata', 'user_id')
    # ### end Alembic commands ###
